### ISSUE TITLE
[Suggestion] ConfigLib + way to store HashMaps in config files

### ISSUE THREAD

**Issue by shmezi** [EinGriefer/Drain#2]
Suggestion:

- Add custom config lib 
- Add a way to store hashmaps easily in a config

**Comment by EinGriefer** [comment]
I added your first suggestion. 😄 Thank you! If you encounter any issues, please create an issue. 
The feature will be "officially" added in the next release. Until then, you have to build Drain yourself to use the new feature! 

You can read the reason why I haven't added your second suggestion here: https://github.com/EinGriefer/Drain/pull/5
If you have an idea, how to realize your second suggestion, just add it yourself. 😄
